project:
  type: book

book:
  title: "Workflows for Spatial Exante Economic Analytics: Selected SOPs"
  author: "Maxwell Mkondiwa (with Jordan Chamberlin and CSISA-EiA Team)"
  date: 23/02/2024
  date-format: long
  
  chapters:
    - index.qmd
    - intro.qmd
    - exploratory_toolkit.qmd
    - spatial_profit_assessment.qmd
    - spatial_optimization_toolkit.qmd
    - spatial_economic_surplus.qmd
    - differentiated_agronomy.qmd
    - summary.qmd
    - references.qmd
  
bibliography: references.bib



format:
  html:
    theme: cosmo

editor: visual

