# References 

Alston, J.M., Norton, G.W., and Pardey, P. 1995. "Science under scarcity: Principles and practice for agricultural research evaluation and priority setting". CAB International. See Chapter 7 (pp. 463-498).

Antle, J.M. 1983. "Testing the stochastic structure of production: A flexible moment-based approach". Journal of Business and Economic Statistics 1(3): 192-201. Doi: 10.1080/07350015.1983.10509339.

Antle, J.M. 2010. "Asymmetry, partial moments and production risk." American Journal of Agricultural Economics 92(5): . Doi: https://doi.org/10.1093/ajae/aaq077.

Athey, S., Tibshirani, J., and Wager, S. 2019. "Generalized Random Forests." The Annals of Statistics 47(2): 1148-1178. Doi: 10.1214/18-AOS1709.

Athey, S., and Wager, S. 2021. "Policy learning with observational data". Econometrica. Url: https://onlinelibrary.wiley.com/doi/abs/10.3982/ECTA15732.

Binswanger, H.P. 1986. "Evaluating Research System Performance and Targeting Research in Land-abundant Areas of Sub-Saharan Africa." World Development 14(4): 469-475. Doi: https://doi.org/10.1016/0305-750X(86)90063-X.

Di Falco, S., Chavas, J., and Smale, M. 2007. "Farmer management of production risk on degraded lands: the role of wheat variety diversity in the Tigray region, Ethiopia." Agricultural Economics 36: 147-156. Doi: https://doi.org/10.1111/j.1574-0862.2007.00194.x.

Di Falco, S., and Chavas, J. 2009. "On crop biodiversity, risk exposure, and food security in the highlands of Ethiopia". American Journal of Agricultural Economics 91(3): 599-611. Doi: https://doi.org/10.1111/j.1467-8276.2009.01265.x.

Hurley, T., Koo, J., and Tesfaye, K. 2018. "Weather risk: how does it change the yield benefits of nitrogen fertilizer and improved maize varieties in sub-Saharan Africa?" Agricultural Economics 49: 711-723. Doi: 10.1111/agec.12454.

Lee, D.R., Edmeades, S., Nys, E., McDonald, A., Janssen, W. 2014. "Developing local adaptation strategies for climate change in agriculture: A priority-setting approach with application to Latin America". Global Environmental Change 29: 78-91. Doi: https://doi.org/10.1016/j.gloenvcha.2014.08.002.

McCullough, E.B., Quinn, J.D., Simons, A.M. 2020. "Profitability of climate-smart soil fertility investment varies widely across sub-Saharan Africa." Nature Food 3:275-285. Doi: https://doi.org/10.1038/s43016-022-00493-z.

